"""initial schema

Revision ID: 53dfb300d441
Revises:
Create Date: 2026-09-20 14:53:31.140712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "53dfb300d441"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_tg_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_audits_action"), "admin_audits", ["action"], unique=False)
    op.create_index(op.f("ix_admin_audits_admin_tg_id"), "admin_audits", ["admin_tg_id"], unique=False)
    op.create_index(op.f("ix_admin_audits_created_at"), "admin_audits", ["created_at"], unique=False)
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_tg_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=True),
        sa.Column("bot_username", sa.String(length=64), nullable=True),
        sa.Column("bot_token_enc", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("plan", sa.String(length=20), nullable=False),
        sa.Column("trial_ends_at", sa.DateTime(), nullable=True),
        sa.Column("paid_until", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id"),
    )
    op.create_index(op.f("ix_tenants_owner_tg_id"), "tenants", ["owner_tg_id"], unique=False)
    op.create_table(
        "identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("official_user_id", sa.BigInteger(), nullable=True),
        sa.Column("alert_text", sa.String(length=200), nullable=False),
        sa.Column("card_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_code", sa.String(length=16), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("rail", sa.String(length=10), nullable=False),
        sa.Column("plan", sa.String(length=20), nullable=False),
        sa.Column("period_days", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=True),
        sa.Column("pay_url", sa.Text(), nullable=True),
        sa.Column("pay_address", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.String(length=128), nullable=True),
        sa.Column("telegram_charge_id", sa.String(length=128), nullable=True),
        sa.Column("txid", sa.String(length=128), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("period_start", sa.DateTime(), nullable=True),
        sa.Column("period_end", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_code", name="uq_code"),
        sa.UniqueConstraint("telegram_charge_id", name="uq_charge"),
        sa.UniqueConstraint("txid", name="uq_txid"),
    )
    op.create_index(op.f("ix_orders_public_code"), "orders", ["public_code"], unique=False)
    op.create_index(op.f("ix_orders_tenant_id"), "orders", ["tenant_id"], unique=False)
    op.create_table(
        "order_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_orders_tenant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_public_code"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("identities")
    op.drop_index(op.f("ix_tenants_owner_tg_id"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_table("settings")
    op.drop_index(op.f("ix_admin_audits_created_at"), table_name="admin_audits")
    op.drop_index(op.f("ix_admin_audits_admin_tg_id"), table_name="admin_audits")
    op.drop_index(op.f("ix_admin_audits_action"), table_name="admin_audits")
    op.drop_table("admin_audits")
    # ### end Alembic commands ###
